### PR TITLE
Update to use argon2 hashing

### PR DESCRIPTION
**Pull request by nicksellen**
As there is some interest in the foodsharing light project now, it seems worth at least making it so you can login and look around :)

This updates the check password code to use the same hash as the foodsharing backend itself uses.

I tried it locally on my docker-compose setup and was able to login. Currently you cannot login on the deployed site anyway (https://beta.light.foodsharing.de).

### CODE REVIEW

**Comment by nicksellen** [comment]
Maybe you can review @RedBeardCode ?

**Comment by nicksellen** [comment]
Note: a few people (around 10/15) have a bcrypt password and they won't be able to log in to fslight.

This is because we switched from md5 -> bcrypt automatically initially. Then switched so it would turn md5 -> argon2. But no process for changing bcrypt -> argon2.

**Comment by RedBeardCode** [comment]
Unfortunately I don't have write access to merge it. Or at least I don't see the merge button.

**Comment by nicksellen** [comment]
Thanks!

**Comment by nicksellen** [comment]
I added you as a collaborator with write access to.

**Pull request merged**
