### PR TITLE
Development

### PR DESCRIPTION
**Pull request by RedBeardCode**
Linting and adding UnitTests.

### CODE REVIEW

**Comment by RedBeardCode** [comment]
Thanks so far.

**Comment by NerdyProjects** [comment]
Sorry for not getting back earlier - I will look into it later :D

**Comment by RedBeardCode** [comment]
N o worries.

**Comment by nicksellen** [comment]
@NerdyProjects reviewed it and it looks really good! ... I had the merge button to hand :)

**Comment by nicksellen** [comment]
Deployment failed due to permissions, we can fix it later today :) ... Although I guess there are no new features to play with anyway.

**Comment by RedBeardCode** [comment]
No hurry with the deployment. It would be enough if we deploy next time with new features.

**Pull request merged**
